# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(gradle_path: "platforms/android/gradlew", task: "test")
  end

  desc "Bundle and sign the app"
  lane :build do
    gradle(
      project_dir: "platforms/android",
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "versionCode" => ENV['VERSION_CODE'],
        "versionName" => ENV['VERSION_NAME'],
        "android.injected.signing.store.file" => ENV['YONA_KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['YONA_KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => "Yona",
        "android.injected.signing.key.password" => ENV['YONA_KEY_PASSWORD'],
      }
    )
  end

  desc "Submit a new Alpha build to Google Play"
  lane :alpha do
    upload_to_play_store(track: 'alpha', aab: 'platforms/android/app/build/outputs/apk/release/app-release.apk')
  end

  desc "Promote the Alpha build to Beta on Google Play"
  lane :beta do
    supply(
           track: "alpha",
           track_promote_to: "beta",
           skip_upload_apk: true,
           skip_upload_metadata: true,
           skip_upload_images: true,
           skip_upload_screenshots: true,
          )
  end

  desc "Promote the Beta build to production on Google Play"
  lane :production do
    supply(
           track: "beta",
           track_promote_to: "production",
           skip_upload_apk: true,
           skip_upload_metadata: true,
           skip_upload_images: true,
           skip_upload_screenshots: true,
          )
  end
end
